steps:
  # Diagnostic: verify what files Cloud Build received
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Dockerfile first line ==="
        head -3 Dockerfile
        echo "=== Backend dir ==="
        ls backend/ 2>/dev/null || echo "NO backend/ directory!"
        echo "=== Root files ==="
        ls -la *.yaml *.yml Dockerfile* nginx.conf 2>/dev/null

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_TAG}'
      - '.'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_TAG}'

substitutions:
  _SERVICE: 'future-skillr'
  _REGION: 'europe-west3'
  _AR_REPO: 'cloud-run-source-deploy'
  _TAG: 'latest'
