-- MVP4: Solid Pod connection metadata (FR-076)
ALTER TABLE users ADD COLUMN IF NOT EXISTS pod_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pod_webid TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pod_provider TEXT DEFAULT 'none';
ALTER TABLE users ADD COLUMN IF NOT EXISTS pod_connected_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pod_last_synced_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pod_sync_status TEXT DEFAULT 'none';
