#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# deploy.sh — Deploy Future SkillR to Cloud Run
#
# Reads config from .env.deploy (generated by gcp-onboard.sh).
# Generates an HTML deployment report in docs/ops/deployments/.
#
# Usage:
#   ./scripts/deploy.sh              # Production deploy
#   ./scripts/deploy.sh staging      # Staging deploy (max 1 instance)
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.deploy"
TARGET="${1:-production}"

# ─── Load config ─────────────────────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
  err ".env.deploy not found. Run first: ./scripts/gcp-onboard.sh"
  exit 1
fi

set -a
while IFS='=' read -r key value; do
  [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
  key=$(echo "$key" | xargs)
  value=$(echo "$value" | xargs)
  [ -n "$key" ] && export "$key=$value"
done < "$ENV_FILE"
set +a

# ─── Validate ────────────────────────────────────────────────────────
REQUIRED_VARS=(GCP_PROJECT_ID GCP_REGION CLOUD_RUN_SERVICE GEMINI_API_KEY DATABASE_URL)
MISSING=()
for var in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!var:-}" ]; then MISSING+=("$var"); fi
done
if [ ${#MISSING[@]} -gt 0 ]; then
  err "Missing in .env.deploy: ${MISSING[*]}"
  err "Run ./scripts/gcp-onboard.sh to configure."
  exit 1
fi

# ─── Prepare ─────────────────────────────────────────────────────────
cd "$PROJECT_ROOT"

if [ "$TARGET" = "staging" ]; then
  SERVICE="${CLOUD_RUN_SERVICE}-staging"
  MAX_INSTANCES=1
else
  SERVICE="$CLOUD_RUN_SERVICE"
  MAX_INSTANCES=10
fi

CURRENT_ACCOUNT=$(gcloud config get-value account 2>/dev/null || echo "unknown")
GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_MSG=$(git log -1 --pretty=format:"%s" 2>/dev/null || echo "")
DEPLOY_START=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

info "Deploying ${BOLD}$SERVICE${NC} (${TARGET})"
echo ""
echo "  Project:    $GCP_PROJECT_ID"
echo "  Region:     $GCP_REGION"
echo "  Service:    $SERVICE"
echo "  Commit:     $GIT_SHA ($GIT_BRANCH)"
echo "  Max inst:   $MAX_INSTANCES"
if [ -n "${CLOUDSQL_CONNECTION_NAME:-}" ]; then
echo "  Cloud SQL:  $CLOUDSQL_CONNECTION_NAME"
fi
echo ""

# ─── Build & Deploy (two-step: local Docker build + Cloud Run) ──────
AR_REPO="cloud-run-source-deploy"
IMAGE_TAG="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPO}/${SERVICE}:${GIT_SHA}"

info "Step 1/2: Building image locally..."
docker build --platform linux/amd64 --build-arg GIT_SHA="$GIT_SHA" -t "$IMAGE_TAG" . && BUILD_OK=true || BUILD_OK=false

if [ "$BUILD_OK" = true ]; then
  info "Pushing image to Artifact Registry..."
  docker push "$IMAGE_TAG" && BUILD_OK=true || BUILD_OK=false
fi

if [ "$BUILD_OK" = false ]; then
  DEPLOY_STATUS="FAILED"
else
  info "Step 2/2: Deploying to Cloud Run..."

  # FR-057/FR-061: Write env vars to temp YAML file (avoids secrets in ps aux)
  # gcloud --env-vars-file expects YAML map format: KEY: "value"
  ENVFILE=$(mktemp -t envvars.XXXXXX.yaml)
  trap 'rm -f "$ENVFILE"' EXIT

  # Helper: write YAML key-value pair with proper quoting
  yaml_kv() { echo "$1: \"$2\"" >> "$ENVFILE"; }

  : > "$ENVFILE"
  yaml_kv DATABASE_URL "${DATABASE_URL}"
  yaml_kv GEMINI_API_KEY "${GEMINI_API_KEY}"
  yaml_kv FIREBASE_API_KEY "${FIREBASE_API_KEY:-}"
  yaml_kv FIREBASE_AUTH_DOMAIN "${FIREBASE_AUTH_DOMAIN:-}"
  yaml_kv FIREBASE_PROJECT_ID "${FIREBASE_PROJECT_ID:-}"
  yaml_kv FIREBASE_STORAGE_BUCKET "${FIREBASE_STORAGE_BUCKET:-}"
  yaml_kv FIREBASE_MESSAGING_SENDER_ID "${FIREBASE_MESSAGING_SENDER_ID:-}"
  yaml_kv FIREBASE_APP_ID "${FIREBASE_APP_ID:-}"
  yaml_kv GCP_PROJECT_ID "${GCP_PROJECT_ID}"
  yaml_kv GCP_REGION "${GCP_REGION}"
  yaml_kv GCP_TTS_REGION "${GCP_TTS_REGION:-europe-west1}"
  yaml_kv GOOGLE_APPLICATION_CREDENTIALS "/app/credentials/vertexai-sa.json"
  yaml_kv HEALTH_CHECK_TOKEN "${HEALTH_CHECK_TOKEN:-}"
  yaml_kv ALLOWED_ORIGINS "${ALLOWED_ORIGINS:-}"
  yaml_kv HONEYCOMB_URL "${HONEYCOMB_URL:-}"
  yaml_kv HONEYCOMB_API_KEY "${HONEYCOMB_API_KEY:-}"
  yaml_kv MEMORY_SERVICE_URL "${MEMORY_SERVICE_URL:-}"
  yaml_kv MEMORY_SERVICE_API_KEY "${MEMORY_SERVICE_API_KEY:-}"
  yaml_kv SOLID_POD_URL "${SOLID_POD_URL:-http://localhost:3000}"
  # FR-127: CSS runs inside the container but needs persistent storage.
  # On staging, disable by default to avoid startup delays.
  if [ "$TARGET" = "staging" ]; then
    yaml_kv SOLID_POD_ENABLED "${SOLID_POD_ENABLED_STAGING:-false}"
  else
    yaml_kv SOLID_POD_ENABLED "${SOLID_POD_ENABLED:-false}"
  fi
  yaml_kv SOLID_POD_ADMIN_EMAIL "${SOLID_POD_ADMIN_EMAIL:-admin@skillr.local}"
  yaml_kv SOLID_POD_ADMIN_PASSWORD "${SOLID_POD_ADMIN_PASSWORD:-skillr}"
  yaml_kv RUN_MIGRATIONS "true"
  yaml_kv STATIC_DIR "/app/static"
  yaml_kv MIGRATIONS_PATH "/app/migrations"

  # Only include admin seed credentials if explicitly set
  [ -n "${ADMIN_SEED_EMAIL:-}" ] && yaml_kv ADMIN_SEED_EMAIL "${ADMIN_SEED_EMAIL}"
  [ -n "${ADMIN_SEED_PASSWORD:-}" ] && yaml_kv ADMIN_SEED_PASSWORD "${ADMIN_SEED_PASSWORD}"

  # Build deploy command with env-vars-file
  DEPLOY_CMD=(gcloud run deploy "$SERVICE"
    --project "$GCP_PROJECT_ID"
    --region "$GCP_REGION"
    --image "$IMAGE_TAG"
    --allow-unauthenticated
    --max-instances "$MAX_INSTANCES"
    --env-vars-file "$ENVFILE"
  )

  # FR-069: Mount Vertex AI SA key from Secret Manager
  VERTEXAI_SECRET="${VERTEXAI_SECRET_NAME:-vertexai-sa-key}"
  if gcloud secrets describe "$VERTEXAI_SECRET" --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
    DEPLOY_CMD+=(--set-secrets "/app/credentials/vertexai-sa.json=${VERTEXAI_SECRET}:latest")
    info "Mounting secret '${VERTEXAI_SECRET}' as /app/credentials/vertexai-sa.json"
  else
    warn "Secret '${VERTEXAI_SECRET}' not found in Secret Manager — AI will be unavailable."
    warn "Run: ./scripts/setup-secrets.sh"
  fi

  # Add Redis URL if configured
  if [ -n "${REDIS_URL:-}" ]; then
    DEPLOY_CMD+=(--set-env-vars "REDIS_URL=${REDIS_URL}")
  fi

  # Add Cloud SQL connection if configured
  if [ -n "${CLOUDSQL_CONNECTION_NAME:-}" ]; then
    DEPLOY_CMD+=(--add-cloudsql-instances "$CLOUDSQL_CONNECTION_NAME")
  fi

  DEPLOY_CMD+=(--quiet)

  "${DEPLOY_CMD[@]}" && DEPLOY_STATUS="SUCCESS" || DEPLOY_STATUS="FAILED"
fi

echo ""

DEPLOY_END=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DEPLOY_URL=""
REVISION=""

if [ "$DEPLOY_STATUS" = "SUCCESS" ]; then
  DEPLOY_URL=$(gcloud run services describe "$SERVICE" \
    --project "$GCP_PROJECT_ID" --region "$GCP_REGION" \
    --format 'value(status.url)' 2>/dev/null || echo "")

  REVISION=$(gcloud run services describe "$SERVICE" \
    --project "$GCP_PROJECT_ID" --region "$GCP_REGION" \
    --format 'value(status.latestReadyRevisionName)' 2>/dev/null || echo "")

  ok "Deployed: ${BOLD}$DEPLOY_URL${NC}"

  # Post-deploy: add Cloud Run URL to Firebase authorized domains
  if [[ -x "$SCRIPT_DIR/setup-oauth-domains.sh" ]]; then
    info "Adding Cloud Run URL to Firebase authorized domains..."
    "$SCRIPT_DIR/setup-oauth-domains.sh" "$DEPLOY_URL" || \
      warn "OAuth domain setup failed (non-fatal). Run manually: make setup-oauth-domains"
  fi
else
  err "Deployment failed."
fi

# ─── Generate HTML report ────────────────────────────────────────────
REPORTS_DIR="$PROJECT_ROOT/docs/ops/deployments"
mkdir -p "$REPORTS_DIR"

TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
REPORT_FILE="$REPORTS_DIR/deploy-${TIMESTAMP}.html"

GIT_LOG_HTML=$(git log --oneline -10 2>/dev/null | \
  sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' | \
  sed 's|^\([a-f0-9]*\) \(.*\)$|<tr><td class="mono">\1</td><td>\2</td></tr>|')

if [ "$DEPLOY_STATUS" = "SUCCESS" ]; then
  STATUS_CLASS="status-success"
else
  STATUS_CLASS="status-failed"
fi

cat > "$REPORT_FILE" <<HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Deploy $TIMESTAMP — Future SkillR</title>
<style>
  :root {
    --bg: #0f172a; --surface: #1e293b; --border: #334155;
    --text: #e2e8f0; --muted: #94a3b8; --accent: #38bdf8;
    --green: #4ade80; --red: #f87171;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: var(--bg); color: var(--text); padding: 2rem; line-height: 1.6; }
  .container { max-width: 900px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .subtitle { color: var(--muted); font-size: 0.875rem; margin-bottom: 2rem; }
  .status-badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px;
                  font-weight: 600; font-size: 0.8rem; text-transform: uppercase; }
  .status-success { background: #064e3b; color: var(--green); }
  .status-failed  { background: #450a0a; color: var(--red); }
  .card { background: var(--surface); border: 1px solid var(--border);
          border-radius: 0.5rem; padding: 1.25rem; margin-bottom: 1rem; }
  .card h2 { font-size: 0.875rem; text-transform: uppercase; letter-spacing: 0.05em;
             color: var(--muted); margin-bottom: 0.75rem; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
  .kv { margin-bottom: 0.5rem; }
  .kv .label { color: var(--muted); font-size: 0.8rem; }
  .kv .value { font-size: 0.95rem; }
  .mono { font-family: 'SF Mono', 'Fira Code', monospace; font-size: 0.85rem; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 0.35rem 0.5rem; border-bottom: 1px solid var(--border); font-size: 0.85rem; }
  td:first-child { width: 80px; color: var(--muted); }
  .quicklinks { display: flex; flex-wrap: wrap; gap: 0.5rem; margin-top: 0.5rem; }
  .quicklinks a { display: inline-block; padding: 0.4rem 0.75rem; background: #0c4a6e;
                  border-radius: 0.375rem; font-size: 0.8rem; font-weight: 500; }
  .quicklinks a:hover { background: #075985; text-decoration: none; }
  .nav { margin-bottom: 1rem; }
  .nav a { font-size: 0.85rem; }
  .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border);
            color: var(--muted); font-size: 0.75rem; text-align: center; }
</style>
</head>
<body>
<div class="container">

<div class="nav"><a href="index.html">&larr; All Deployments</a></div>

<h1>Deployment Report <span class="status-badge $STATUS_CLASS">$DEPLOY_STATUS</span></h1>
<p class="subtitle">$TIMESTAMP &mdash; $TARGET &mdash; Future SkillR</p>

<div class="grid">
  <div class="card">
    <h2>Deployment</h2>
    <div class="kv"><div class="label">Service</div><div class="value">$SERVICE</div></div>
    <div class="kv"><div class="label">Revision</div><div class="value mono">${REVISION:-N/A}</div></div>
    <div class="kv"><div class="label">Project</div><div class="value mono">$GCP_PROJECT_ID</div></div>
    <div class="kv"><div class="label">Region</div><div class="value">$GCP_REGION</div></div>
    <div class="kv"><div class="label">URL</div><div class="value"><a href="${DEPLOY_URL:-#}" target="_blank">${DEPLOY_URL:-N/A}</a></div></div>
  </div>
  <div class="card">
    <h2>Source</h2>
    <div class="kv"><div class="label">Git SHA</div><div class="value mono">$GIT_SHA</div></div>
    <div class="kv"><div class="label">Branch</div><div class="value mono">$GIT_BRANCH</div></div>
    <div class="kv"><div class="label">Message</div><div class="value">$(echo "$GIT_MSG" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')</div></div>
    <div class="kv"><div class="label">Deployer</div><div class="value">$CURRENT_ACCOUNT</div></div>
    <div class="kv"><div class="label">Started</div><div class="value mono">$DEPLOY_START</div></div>
    <div class="kv"><div class="label">Finished</div><div class="value mono">$DEPLOY_END</div></div>
  </div>
</div>

<div class="card">
  <h2>Quick Links</h2>
  <div class="quicklinks">
    <a href="${DEPLOY_URL:-#}" target="_blank">Live App</a>
    <a href="https://console.cloud.google.com/run/detail/$GCP_REGION/$SERVICE/revisions?project=$GCP_PROJECT_ID" target="_blank">Revisions</a>
    <a href="https://console.cloud.google.com/run/detail/$GCP_REGION/$SERVICE/logs?project=$GCP_PROJECT_ID" target="_blank">Logs</a>
    <a href="https://console.cloud.google.com/cloud-build/builds?project=$GCP_PROJECT_ID" target="_blank">Build History</a>
    <a href="https://console.cloud.google.com/artifacts/docker/$GCP_PROJECT_ID/$GCP_REGION/cloud-run-source-deploy?project=$GCP_PROJECT_ID" target="_blank">Images</a>
    <a href="https://console.cloud.google.com/sql?project=$GCP_PROJECT_ID" target="_blank">Cloud SQL</a>
    <a href="https://console.firebase.google.com/project/$GCP_PROJECT_ID" target="_blank">Firebase</a>
  </div>
</div>

<div class="card">
  <h2>Recent Commits</h2>
  <table>
$GIT_LOG_HTML
  </table>
</div>

<div class="footer">
  Generated by <code>scripts/deploy.sh</code> on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
</div>

</div>
</body>
</html>
HTMLEOF

ok "Report: docs/ops/deployments/deploy-${TIMESTAMP}.html"

# ─── Rebuild deployment index ────────────────────────────────────────
INDEX_FILE="$REPORTS_DIR/index.html"

ROWS=""
for f in $(ls -t "$REPORTS_DIR"/deploy-*.html 2>/dev/null); do
  BASENAME=$(basename "$f")
  TS="${BASENAME#deploy-}"
  TS="${TS%.html}"
  DISPLAY_TS="${TS:0:4}-${TS:4:2}-${TS:6:2} ${TS:9:2}:${TS:11:2}:${TS:13:2}"
  if grep -q "status-success" "$f" 2>/dev/null; then
    BADGE='<span class="badge-ok">SUCCESS</span>'
  else
    BADGE='<span class="badge-fail">FAILED</span>'
  fi
  ROWS="${ROWS}    <tr><td class=\"mono\">$DISPLAY_TS</td><td>$BADGE</td><td><a href=\"$BASENAME\">$BASENAME</a></td></tr>
"
done

cat > "$INDEX_FILE" <<IDXEOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Deployment History — Future SkillR</title>
<style>
  :root { --bg: #0f172a; --surface: #1e293b; --border: #334155;
          --text: #e2e8f0; --muted: #94a3b8; --accent: #38bdf8;
          --green: #4ade80; --red: #f87171; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: var(--bg); color: var(--text); padding: 2rem; }
  .container { max-width: 800px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .subtitle { color: var(--muted); font-size: 0.875rem; margin-bottom: 2rem; }
  table { width: 100%; border-collapse: collapse; background: var(--surface);
          border: 1px solid var(--border); border-radius: 0.5rem; overflow: hidden; }
  th { text-align: left; padding: 0.6rem 0.75rem; background: #0f172a;
       font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;
       color: var(--muted); border-bottom: 1px solid var(--border); }
  td { padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--border); font-size: 0.85rem; }
  .mono { font-family: 'SF Mono', 'Fira Code', monospace; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  .badge-ok { background: #064e3b; color: var(--green); padding: 0.15rem 0.5rem;
              border-radius: 9999px; font-size: 0.7rem; font-weight: 600; }
  .badge-fail { background: #450a0a; color: var(--red); padding: 0.15rem 0.5rem;
                border-radius: 9999px; font-size: 0.7rem; font-weight: 600; }
  .footer { margin-top: 2rem; color: var(--muted); font-size: 0.75rem; text-align: center; }
  .empty { padding: 2rem; text-align: center; color: var(--muted); }
</style>
</head>
<body>
<div class="container">
<h1>Deployment History</h1>
<p class="subtitle">Future SkillR &mdash; All Cloud Run deployments (newest first)</p>
<table>
  <thead><tr><th>Timestamp</th><th>Status</th><th>Report</th></tr></thead>
  <tbody>
$ROWS
  </tbody>
</table>
<div class="footer">Auto-generated by <code>scripts/deploy.sh</code></div>
</div>
</body>
</html>
IDXEOF

ok "Index: docs/ops/deployments/index.html"
